name: CI
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    container: node:12
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:ci
